export const moroccanCities = [
  "Casablanca",
  "Rabat",
  "Marrakech",
  "Tanger",
  "Fès",
  "Agadir",
  "Salé",
  "Meknès",
  "Oujda",
  "Kénitra",
  "Tétouan",
  "Témara",
  "Safi",
  "Mohammédia",
  "El Jadida",
  "Béni Mellal",
  "Nador",
  "Taza",
  "Khouribga",
  "Settat",
  "Berrechid",
  "Khémisset",
  "Guelmim",
  "Larache",
  "Ksar El Kebir",
  "Dakhla",
  "Laâyoune",
  "Errachidia",
  "Berkane",
  "Taroudant",
  "Ouarzazate",
  "Essaouira",
  "Al Hoceïma",
  "Tiflet",
  "Sidi Slimane",
  "Sidi Kacem",
  "Youssoufia",
  "Tan-Tan",
  "Oued Zem",
  "Sefrou",
  "Fnideq",
  "Martil",
  "M'diq",
  "Asilah",
  "Midelt",
  "Azrou",
  "Ifrane",
  "Chefchaouen",
  "Autre ville / Autre région"
] as const;

export type MoroccanCity = (typeof moroccanCities)[number];
